idf_component_register(
    SRCS
        "main.c"
        "audio_i2s.c"
        "espnow_protocol.c"
        "ptt_button.c"
        "status_led.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_wifi
        nvs_flash
        driver
        esp_driver_i2s
        esp_driver_gpio
        esp_driver_rmt
        led_strip
        freertos
        esp_ringbuf
        esp_common
        esp_timer
)
